### ISSUE TITLE
Possible suggestion for GPUs with only one performance state (P100, V100, etc)

### ISSUE THREAD

**Issue by city96** [sasha0552/nvidia-pstated#6]
I've been using this utility for a while now, and it works great with the two Tesla P40 GPUs I have in this system, but the third (Volta based) Tesla V100 card seems unsupported due to only having one default (P0) power state. [[1]](https://forums.developer.nvidia.com/t/why-the-pstate-of-v100-does-not-change-always-p0/116746) [[2]](https://old.reddit.com/r/nvidia/comments/17aaeuh/the_nvidia_tesladatacenter_gpu_amateur_info_dump/).

Even with just one pstate, the core clocks still go up when the card is idle with an LLM model loaded in VRAM, raising the idle power draw from ~33W to ~45W, which is *just* enough to raise the system fan speed to a level where it's annoying lol.

While looking around for solutions, I found [this stackoverflow post](https://stackoverflow.com/a/64729952) about locking clock speeds for profiling. I can confirm that locking the clock speeds to the *lowest* level does indeed get the power usage back down (even when setting the clocks after CUDA context creation with the model already loaded).

So technically the same logic could be used as with pstates, except via `nvidia-smi -i 0 -ac [lowest mem/gpu clock available]` for idle, followed by `nvidia-smi -i 0 -acp` to unlock both and return to a high/auto power state. This could work as a "fallback" mode for when setting the pstate fails on a GPU.

I did some minimal digging to see how hard it would be to add, but I have basically zero experience with `nvapi`. I found [`nvmlDeviceSetApplicationsClocks`](https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceCommands.html#group__nvmlDeviceCommands_1gc2a9a8db6fffb2604d27fd67e8d5d87f) - though that's `nvml` not `nvapi`, and I didn't find anything relevant in `nvapi` other than `NvAPI_GPU_GetAllClockFrequencies` (with no obvious way to set it).

So yeah, this is more just brainstorming than anything. Feel free to close as not planned if you think it's not really feasible.

<details>
<summary> Default error log when not excluding GPU 0: </summary>

```
./nvidia-pstated
ids = N/A (0)
iterationsBeforeSwitch = 30
performanceStateHigh = 16
performanceStateLow = 8
sleepInterval = 100
temperatureThreshold = 80
0. Tesla V100S-PCIE-32GB (GPU id = 0)
1. Tesla P40 (GPU id = 1)
2. Tesla P40 (GPU id = 2)
Managing 3 GPUs...
NvAPI_GPU_SetForcePstate(nvapiDevices[i], pstateId, 0): NVAPI_ERROR
```

</details>

<details>
<summary> Output for `nvidia-smi -q -d SUPPORTED_CLOCKS` </summary>

```
Attached GPUs                             : 3
GPU 00000000:43:00.0
    Supported Clocks
        Memory                            : 1107 MHz
            Graphics                      : 1597 MHz
            Graphics                      : 1590 MHz
            Graphics                      : 1582 MHz
            Graphics                      : 1575 MHz
            Graphics                      : 1567 MHz
            Graphics                      : 1560 MHz
            Graphics                      : 1552 MHz
            Graphics                      : 1545 MHz
            Graphics                      : 1537 MHz
            Graphics                      : 1530 MHz
            Graphics                      : 1522 MHz
            Graphics                      : 1515 MHz
            Graphics                      : 1507 MHz
            Graphics                      : 1500 MHz
            Graphics                      : 1492 MHz
            Graphics                      : 1485 MHz
            Graphics                      : 1477 MHz
            Graphics                      : 1470 MHz
            Graphics                      : 1462 MHz
            Graphics                      : 1455 MHz
            Graphics                      : 1447 MHz
            Graphics                      : 1440 MHz
            Graphics                      : 1432 MHz
            Graphics                      : 1425 MHz
            Graphics                      : 1417 MHz
            Graphics                      : 1410 MHz
            Graphics                      : 1402 MHz
            Graphics                      : 1395 MHz
            Graphics                      : 1387 MHz
            Graphics                      : 1380 MHz
            Graphics                      : 1372 MHz
            Graphics                      : 1365 MHz
            Graphics                      : 1357 MHz
            Graphics                      : 1350 MHz
            Graphics                      : 1342 MHz
            Graphics                      : 1335 MHz
            Graphics                      : 1327 MHz
            Graphics                      : 1320 MHz
            Graphics                      : 1312 MHz
            Graphics                      : 1305 MHz
            Graphics                      : 1297 MHz
            Graphics                      : 1290 MHz
            Graphics                      : 1282 MHz
            Graphics                      : 1275 MHz
            Graphics                      : 1267 MHz
            Graphics                      : 1260 MHz
            Graphics                      : 1252 MHz
            Graphics                      : 1245 MHz
            Graphics                      : 1237 MHz
            Graphics                      : 1230 MHz
            Graphics                      : 1222 MHz
            Graphics                      : 1215 MHz
            Graphics                      : 1207 MHz
            Graphics                      : 1200 MHz
            Graphics                      : 1192 MHz
            Graphics                      : 1185 MHz
            Graphics                      : 1177 MHz
            Graphics                      : 1170 MHz
            Graphics                      : 1162 MHz
            Graphics                      : 1155 MHz
            Graphics                      : 1147 MHz
            Graphics                      : 1140 MHz
            Graphics                      : 1132 MHz
            Graphics                      : 1125 MHz
            Graphics                      : 1117 MHz
            Graphics                      : 1110 MHz
            Graphics                      : 1102 MHz
            Graphics                      : 1095 MHz
            Graphics                      : 1087 MHz
            Graphics                      : 1080 MHz
            Graphics                      : 1072 MHz
            Graphics                      : 1065 MHz
            Graphics                      : 1057 MHz
            Graphics                      : 1050 MHz
            Graphics                      : 1042 MHz
            Graphics                      : 1035 MHz
            Graphics                      : 1027 MHz
            Graphics                      : 1020 MHz
            Graphics                      : 1012 MHz
            Graphics                      : 1005 MHz
            Graphics                      : 997 MHz
            Graphics                      : 990 MHz
            Graphics                      : 982 MHz
            Graphics                      : 975 MHz
            Graphics                      : 967 MHz
            Graphics                      : 960 MHz
            Graphics                      : 952 MHz
            Graphics                      : 945 MHz
            Graphics                      : 937 MHz
            Graphics                      : 930 MHz
            Graphics                      : 922 MHz
            Graphics                      : 915 MHz
            Graphics                      : 907 MHz
            Graphics                      : 900 MHz
            Graphics                      : 892 MHz
            Graphics                      : 885 MHz
            Graphics                      : 877 MHz
            Graphics                      : 870 MHz
            Graphics                      : 862 MHz
            Graphics                      : 855 MHz
            Graphics                      : 847 MHz
            Graphics                      : 840 MHz
            Graphics                      : 832 MHz
            Graphics                      : 825 MHz
            Graphics                      : 817 MHz
            Graphics                      : 810 MHz
            Graphics                      : 802 MHz
            Graphics                      : 795 MHz
            Graphics                      : 787 MHz
            Graphics                      : 780 MHz
            Graphics                      : 772 MHz
            Graphics                      : 765 MHz
            Graphics                      : 757 MHz
            Graphics                      : 750 MHz
            Graphics                      : 742 MHz
            Graphics                      : 735 MHz
            Graphics                      : 727 MHz
            Graphics                      : 720 MHz
            Graphics                      : 712 MHz
            Graphics                      : 705 MHz
            Graphics                      : 697 MHz
            Graphics                      : 690 MHz
            Graphics                      : 682 MHz
            Graphics                      : 675 MHz
            Graphics                      : 667 MHz
            Graphics                      : 660 MHz
            Graphics                      : 652 MHz
            Graphics                      : 645 MHz
            Graphics                      : 637 MHz
            Graphics                      : 630 MHz
            Graphics                      : 622 MHz
            Graphics                      : 615 MHz
            Graphics                      : 607 MHz
            Graphics                      : 600 MHz
            Graphics                      : 592 MHz
            Graphics                      : 585 MHz
            Graphics                      : 577 MHz
            Graphics                      : 570 MHz
            Graphics                      : 562 MHz
            Graphics                      : 555 MHz
            Graphics                      : 547 MHz
            Graphics                      : 540 MHz
            Graphics                      : 532 MHz
            Graphics                      : 525 MHz
            Graphics                      : 517 MHz
            Graphics                      : 510 MHz
            Graphics                      : 502 MHz
            Graphics                      : 495 MHz
            Graphics                      : 487 MHz
            Graphics                      : 480 MHz
            Graphics                      : 472 MHz
            Graphics                      : 465 MHz
            Graphics                      : 457 MHz
            Graphics                      : 450 MHz
            Graphics                      : 442 MHz
            Graphics                      : 435 MHz
            Graphics                      : 427 MHz
            Graphics                      : 420 MHz
            Graphics                      : 412 MHz
            Graphics                      : 405 MHz
            Graphics                      : 397 MHz
            Graphics                      : 390 MHz
            Graphics                      : 382 MHz
            Graphics                      : 375 MHz
            Graphics                      : 367 MHz
            Graphics                      : 360 MHz
            Graphics                      : 352 MHz
            Graphics                      : 345 MHz
            Graphics                      : 337 MHz
            Graphics                      : 330 MHz
            Graphics                      : 322 MHz
            Graphics                      : 315 MHz
            Graphics                      : 307 MHz
            Graphics                      : 300 MHz
            Graphics                      : 292 MHz
            Graphics                      : 285 MHz
            Graphics                      : 277 MHz
            Graphics                      : 270 MHz
            Graphics                      : 262 MHz
            Graphics                      : 255 MHz
            Graphics                      : 247 MHz
            Graphics                      : 240 MHz
            Graphics                      : 232 MHz
            Graphics                      : 225 MHz
            Graphics                      : 217 MHz
            Graphics                      : 210 MHz
            Graphics                      : 202 MHz
            Graphics                      : 195 MHz
            Graphics                      : 187 MHz
            Graphics                      : 180 MHz
            Graphics                      : 172 MHz
            Graphics                      : 165 MHz
            Graphics                      : 157 MHz
            Graphics                      : 150 MHz
            Graphics                      : 142 MHz
            Graphics                      : 135 MHz

GPU 00000000:87:00.0
    Supported Clocks
        Memory                            : 3615 MHz
[Rest of log removed since these are for the P40s]
```

</details>

**Comment by sasha0552** [comment]
Hi!

I considered this approach when I originally looked into reducing power consumption on the P40. But unfortunately Pascal does not support setting core clock speeds with `nvidia-smi -ac`.

It's okay that you only found setter in `nvml`, `nvapi` is only used to force pstate, so this application uses both.

Overall, this would not be difficult to implement and I will consider it. Though as a separate command line flag + documentation, since there is no easy way to determine if the GPU supports pstate switching (or `nvidia-smi -ac` at all).

**Comment by city96** [comment]
Thank you for considering it. I think a CLI flag would work perfectly fine, and sounds like it'd make the most sense for a clean implementation (since the amount of users running on cards without pstate support is most likely fairly low, and mixed setups are even more of an edgecase).

I'm not super great with C code but LMK if I can help out lol.

**Comment by mateuszdrab** [comment]
Does P40 support any other P states that 0 and 8? I can't get any other state to work actually.

**Comment by PabloSoage** [comment]
I've been following this project for a while, mainly because of my interest in this issue. I have a server with 4x V100 sxm2, and they consume 45-50W each at idle, with only the P0 state available. A little while ago, I forked the repository and made some experimental changes that I think might work, but I haven't had time to test them yet. I'll try it on my server tomorrow or one of these days to see how it goes, but I don't have much time due to other work and exams.
In case anyone is interested, this is the fork at the moment, but I can't guarantee it will work: https://github.com/PabloSoage/nvidia-pstated.

P.S. I'm not active on my profile because the repositories I work on are private, but I'm not a bot or anything, haha.

![Image](https://github.com/user-attachments/assets/005062af-f5a3-4b3d-b1ef-f70bdb119cca)

**Comment by PabloSoage** [comment]
I've already tested it and it works.
I've verified that the GPU clocks are reduced from 1530MHz to 135MHz. However, the memory only has 877MHz available, so it's not affected.
I haven't noticed any reduction in power consumption for either GPU even with the clocks at 135MHz.

![Image](https://github.com/user-attachments/assets/65a44da4-3f73-495e-87db-4eccec07e06f)

**Comment by richginsberg** [comment]
@PabloSoage Thank you for this.

While idle watts are 39-42W per V100 SXM2 both ways, With llama.cpp it was 54-59w idle model loaded.
With your PR. idle watts remain the same, but model loaded idle watts have dropped 16-18w per GPU.

IDLE
<img width="735" height="386" alt="Image" src="https://github.com/user-attachments/assets/1204836b-1658-4a62-b4e2-28f0acc7d586" />

IDLE LOADED (default)
<img width="738" height="391" alt="Image" src="https://github.com/user-attachments/assets/d4ea827f-b1c9-478f-a4d8-c004b1e7dc01" />

IDLE LOADED nvidia-pstated PR
<img width="739" height="386" alt="Image" src="https://github.com/user-attachments/assets/cca887a4-4a30-4102-a484-ae2348c448a5" />

**Comment by avidwriter** [comment]
@PabloSoage  i ran your modified code on a system with a 3090 and now the 3090 is stuck in P0 without the script running. i tried the -rgc option and various nvidia-smi things. 

is there anything else to get normal pstate swtiching back on linux? thanks

**Comment by sasha0552** [comment]
@avidwriter Try using [nvidia-pstate](https://github.com/sasha0552/nvidia-pstate), specifically `nvidia-pstate -ps 16`

**Comment by avidwriter** [comment]
> [@avidwriter](https://github.com/avidwriter) Try using [nvidia-pstate](https://github.com/sasha0552/nvidia-pstate), specifically `nvidia-pstate -ps 16`

@sasha0552  thanks it says `Performance state has been set successfully for gpu #2` but it doesn't seem to have any effect even after a reboot

**Comment by sasha0552** [comment]
Have you tried `nvidia-smi -rac`? If so, try [this branch](https://github.com/sasha0552/nvidia-pstated/tree/temp-fixpstate), it might help. It tries to reset the memclock and pstate (and then just exits).

**Comment by avidwriter** [comment]
@sasha0552 

it looks like that's not supported on 3090. 

nvidia-smi gives
`> sudo nvidia-smi -i 2 -rac
Setting applications clocks is not supported for GPU 00000000:81:00.0.
Treating as warning and moving on.
All done.
`

here's the output from that branch:
`> sudo ./build/nvidia-pstated -i 2
ids = 2 (1)
iterationsBeforeSwitch = 30
performanceStateHigh = 16
performanceStateLow = 8
clockFreqMemHigh = 0
clockFreqGpuHigh = 0
clockFreqMemLow = 0
clockFreqGpuLow = 0
enableClockFallback = true
sleepInterval = 100
temperatureThreshold = 80
0. NVIDIA GeForce RTX 3090 (GPU id = 2)
Managing 1 GPUs...
GPU 2 supported memory clock: 9501 MHz
GPU 2 supported memory clock: 5001 MHz
GPU 2 supported memory clock: 810 MHz
GPU 2 supported memory clock: 405 MHz
GPU 2 lowest clocks: Memory 405 MHz, GPU 210 MHz
nvmlDeviceResetApplicationsClocks(nvmlDevices[i]): Not Supported
`

**Comment by sasha0552** [comment]
Strange, do you have the `nvidia-persistenced` service running? Can you set the clocks using `nvidia-smi`? If so, perhaps the 3090 only supports clock adjustment, but not reset. Perhaps this function has a magic value, like pstate 16.

**Comment by avidwriter** [comment]
I disabled the persistence mode on the 3090 and -rgc said OK this time but still stuck at P0. thanks for trying!

**Comment by petruchito** [comment]
> IDLE LOADED nvidia-pstated PR <img alt="Image" width="739" height="386" src="https://private-user-images.githubusercontent.com/819865/530516581-cca887a4-4a30-4102-a484-ae2348c448a5.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODI1NjMyMjQsIm5iZiI6MTc4MjU2MjkyNCwicGF0aCI6Ii84MTk4NjUvNTMwNTE2NTgxLWNjYTg4N2E0LTRhMzAtNDEwMi1hNDg0LWFlMjM0OGM0NDhhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDYyN1QxMjIyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzZjMjhhODg4YTI4YzM1ZDhhOWE2MDVmZTMxY2M2NDMzMWM4ZDQ4NWY3YjUxMDFlZGNmNjk3NmI0MDhiZGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.JUGPiEgzJaC1p6ry2VLA4RzMVrG8gE9sazr03SEZZ60">

Not sure what's the reason, but mine in idling at 40W as well, with model loaded, stock driver and default settings(SXM2 on PCIe adapter):
```
Every 2.0s: nvidia-smi; echo; vmstat -S M 1 1; echo; free -h; echo; ps aux --sort=-%cpu | head -n 6                                        llm: Sat Jun 27 15:22:58 2026

Sat Jun 27 15:22:58 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.163.01             Driver Version: 550.163.01     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla V100-SXM2-16GB           On  |   00000000:01:00.0 Off |                    0 |
| N/A   34C    P0             40W /  300W |   15925MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A       956      C   ...to/llama.cpp/build/bin/llama-server      15874MiB |
+-----------------------------------------------------------------------------------------+

procs -----------memory---------- ---swap-- -----io---- -system-- -------cpu-------
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st gu
 0  0      0    700     28  26943    0    0   839     4  105    0  1  0 98  0  0  0

               total        used        free      shared  buff/cache   available
Mem:            30Gi        28Gi       700Mi        24Gi        26Gi       2.0Gi
Swap:          3.1Gi       768Ki       3.1Gi

USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
petruch+     956 10.8 89.6 54487992 28701948 pts/0 SLl+ 02:43  82:14 /home/petruchito/llama.cpp/build/bin/llama-server -m /llama_models/Qwen3.6-35B-A3B-UD-Q8_K_XL.gguf
root          80  0.4  0.0      0     0 ?        S    02:42   3:37 [kcompactd0]
root       14540  0.0  0.0   6828  3604 pts/2    S+   12:58   0:04 watch -n 2 nvidia-smi; echo; vmstat -S M 1 1; echo; free -h; echo; ps aux --sort=-%cpu | head -n 6
root         838  0.0  0.0      0     0 ?        S    02:42   0:17 [nv_queue]
root          93  0.0  0.0      0     0 ?        S    02:42   0:09 [kswapd0]
```
